spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: log-group
      properties:
        spring:
          json:
           trusted:
            packages: "*"
    producer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"


